name: Deploy on Data Update

on:
    repository_dispatch:
        types: [data-updated]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout main repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Build tools
              run: |
                  cd tools
                  CGO_ENABLED=0 go build -o sfwatch -buildvcs=false ./cmd/sfwatch

                  - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
        env:
          VITE_SF_STAMPS_DATA_URL: "./data/stamps.json"
          VITE_SF_SHOPS_DATA_URL: "./data/shops.json"

            - name: Generate site with updated data
              run: |
                  mkdir -p ./site-output
                  echo "Generating site with updated data..."

                  # Запускаем sfwatch в фоне
                  ./tools/sfwatch -r ./site-output -f ./frontend/dist --update-period=30s --disable-rusmarka &
                  SFWATCH_PID=$!

                  echo "Waiting for site generation..."

                  # Ждем пока сгенерируются страницы (максимум 10 минут)
                  for i in {1..120}; do
                    if [ -d "./site-output/pages" ] && [ "$(ls -A ./site-output/pages 2>/dev/null)" ]; then
                      echo "Site generation completed successfully!"
                      break
                    fi
                    echo "Waiting for site generation... (${i}/120)"
                    sleep 5
                  done

                  # Останавливаем sfwatch
                  echo "Stopping sfwatch..."
                  kill $SFWATCH_PID 2>/dev/null || true
                  wait $SFWATCH_PID 2>/dev/null || true

                  if [ ! -d "./site-output/pages" ] || [ ! "$(ls -A ./site-output/pages 2>/dev/null)" ]; then
                    echo "ERROR: pages directory not found or empty"
                    ls -la ./site-output/ 2>/dev/null || echo "site-output directory doesn't exist"
                    exit 1
                  fi

                  echo "Site generation completed"

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./site-output/pages"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
