name: Deploy Frontend Only (No Data)

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Build frontend
              run: |
                  cd frontend
                  npm ci
                  npm run build
              env:
                  VITE_SF_STAMPS_DATA_URL: "./data/stamps.json"
                  VITE_SF_SHOPS_DATA_URL: "./data/shops.json"

            - name: Deploy frontend only (no data)
              run: |
                  mkdir -p ./site-output/pages
                  cp -r frontend/dist/* ./site-output/pages/
                  mkdir -p ./site-output/pages/data
                  # Создаем заглушки для работы фронтенда
                  echo '[]' > ./site-output/pages/data/stamps.json
                  echo '[]' > ./site-output/pages/data/shops.json
                  echo "This is a frontend-only deployment. Use 'Quick Deploy' or 'Update Data and Deploy' for full functionality." > ./site-output/pages/data/README.txt

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./site-output/pages"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
